name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: 'Thank you for sharing! We appreciate your effort and will review your issue/feature request as soon as possible. Stay tuned for updates! 🚀'
          pr-message: 'Thank you for your contribution! We appreciate your effort and will review your PR as soon as possible. Stay tuned for updates! 🚀'
